// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFaTow7qPvFhp8qOqueWamis2b9DHs808',
    appId: '1:404154651244:android:cbf4f6bcdcc1b714513e49',
    messagingSenderId: '404154651244',
    projectId: 'calculator-app-40c80',
    storageBucket: 'calculator-app-40c80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlO7fpWFQ2fKdktBeRsA-SenPLA7-j02A',
    appId: '1:404154651244:ios:1ca3abf8849e340d513e49',
    messagingSenderId: '404154651244',
    projectId: 'calculator-app-40c80',
    storageBucket: 'calculator-app-40c80.appspot.com',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlO7fpWFQ2fKdktBeRsA-SenPLA7-j02A',
    appId: '1:404154651244:ios:1ca3abf8849e340d513e49',
    messagingSenderId: '404154651244',
    projectId: 'calculator-app-40c80',
    storageBucket: 'calculator-app-40c80.appspot.com',
    iosBundleId: 'com.example.helloFlutter',
  );
}
